//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;


namespace Brokers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointments
    {
        public int idAppointments { get; set; }

        [Display(Name = "Date et heure")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        [Required(ErrorMessage = "Veuillez préciser un horaire")]
        public System.DateTime dateHour { get; set; }

        [Display(Name = "Sujet du rdv")]
        public string subject { get; set; }

        [Display(Name = "Client")]
        public int idCustomers { get; set; }

        [Display(Name = "Courtier")]
        public int idBroker { get; set; }
    
        public virtual brokers brokers { get; set; }
        public virtual customers customers { get; set; }
    }
}
